version: 2

sources:
  - name: QWT_RAW
    database: "{{env_var('DBT_SOURCEDB', 'QWT_ANALYTICS')}}"
    schema: "{{env_var('DBT_SOURCESCHEMA', 'RAW')}}"
    tables:
      - name: Customers
      - name: Products
      - name: Orders
      - name: OrderDetails
      - name: Suppliers
      - name: Shipments

  - name: QWT_RAW
    database: "{{env_var('DBT_SOURCEDB', 'QWT_ANALYTICS')}}"
    schema: RAW_GD
    tables:
      - name: products






